fixup

diff --git a/hail/Makefile b/hail/Makefile
--- a/hail/Makefile
+++ b/hail/Makefile
@@ -236,12 +236,12 @@ TAG_EXISTS = $(shell git ls-remote --exit-code --tags origin $(HAIL_PIP_VERSION)
 check-tag:
 	if [ -z "$(TAG_EXISTS)" ]; then echo "ERROR: tag $(HAIL_PIP_VERSION) already exists"; exit 1; fi
 
-annotation_db_json_url := gs://hail-common/annotationdb/$(HAIL_PIP_VERSION)/annotationdb.json
+annotation_db_json_url := gs://hail-common/annotationdb/$(HAIL_PIP_VERSION)/annotation_db.json
 .PHONY: deploy-annotation-db
 deploy-annotation-db:
-	! gsutil ls $(annotation_db_json_url) && \
-    gsutil cp python/hail/experimental/annotation_db.json $(annotation_db_json_url) || \
-    echo "ERROR: annotation db $(HAIL_PIP_VERSION) already exists, refusing to overwrite" && exit 1
+	(! gsutil ls $(annotation_db_json_url) >/dev/null 2>/dev/null && \
+    gsutil cp python/hail/experimental/annotation_db.json $(annotation_db_json_url)) || \
+    (echo "ERROR: annotation db $(HAIL_PIP_VERSION) already exists, refusing to overwrite" && exit 1)
 
 GITHUB_RELEASE_URL = https://github.com/hail-is/hail/releases/new
 .PHONY: tag
