[build] stop evaluating upload-qob-jar variables on makefile parsing
Requires network requests -- I had to comment this out to build
during a power outage :)

diff --git a/hail/Makefile b/hail/Makefile
--- a/hail/Makefile
+++ b/hail/Makefile
@@ -65,21 +65,6 @@ EGG := build/deploy/dist/hail-$(HAIL_PIP_VERSION)-py3.6.egg
 
 GRADLE_ARGS += -Dscala.version=$(SCALA_VERSION) -Dspark.version=$(SPARK_VERSION) -Delasticsearch.major-version=$(ELASTIC_MAJOR_VERSION)
 
-QUERY_STORAGE_URI = $(shell kubectl get secret global-config --template={{.data.query_storage_uri}} | base64 --decode)
-TEST_STORAGE_URI = $(shell kubectl get secret global-config --template={{.data.test_storage_uri}} | base64 --decode)
-TOKEN := $(shell cat /dev/urandom 2> /dev/null | LC_ALL=C tr -dc 'a-z0-9' 2> /dev/null | head -c 12)
-
-ifeq ($(NAMESPACE),default)
-ifeq ($(UPLOAD_RELEASE_JAR),true)
-# This should only be used if the normal CI deploy process fails and you need to upload a JAR to the
-# expected location for our users.
-JAR_LOCATION = $(QUERY_STORAGE_URI)/jars/$(REVISION).jar
-else
-JAR_LOCATION = $(QUERY_STORAGE_URI)/jars/$(shell whoami)/$(TOKEN)/$(REVISION).jar
-endif
-else
-JAR_LOCATION = $(TEST_STORAGE_URI)/$(NAMESPACE)/jars/$(TOKEN)/$(REVISION).jar
-endif
 CLOUD_HAIL_TEST_RESOURCES_PREFIX = $(TEST_STORAGE_URI)/$(shell whoami)/hail-test-resources
 CLOUD_HAIL_TEST_RESOURCES_DIR = $(CLOUD_HAIL_TEST_RESOURCES_PREFIX)/test/resources/
 CLOUD_HAIL_DOCTEST_DATA_DIR = $(CLOUD_HAIL_TEST_RESOURCES_PREFIX)/doctest/data/
@@ -307,10 +292,29 @@ upload-qob-test-resources: $(JAR_TEST_SOURCES)
 # target must be run at least once a day if using a dev NAMESPACE.
 # To trigger this target to re-run,
 # > rm upload-qob-jar
+# call this like: make upload-qob-jar NAMESPACE=default
+upload-qob-jar: SPARK_VERSION := 3.2.1
 upload-qob-jar: $(SHADOW_JAR)
-	! [ -z $(NAMESPACE) ]  # call this like: make upload-qob-jar NAMESPACE=default
-	gcloud storage cp $(SHADOW_JAR) $(JAR_LOCATION)
-	echo $(JAR_LOCATION) > $@
+    set -e ;\
+    ! [ -z "$(NAMESPACE)" ] ;\
+    QUERY_STORAGE_URI=$$(kubectl get secret global-config --template={{.data.query_storage_uri}} | base64 --decode) ;\
+    TEST_STORAGE_URI=$$(kubectl get secret global-config --template={{.data.test_storage_uri}} | base64 --decode) ;\
+    TOKEN=$$(cat /dev/urandom | LC_ALL=C tr -dc 'a-z0-9' | head -c 12) ;\
+    if [ $(NAMESPACE) -eq default ] \
+    then \
+    if [ $(UPLOAD_RELEASE_JAR) -eq true ] \
+    then \
+    # This should only be used if the normal CI deploy process fails and you need to upload a JAR to the
+    # expected location for our users.
+    JAR_LOCATION=$$((QUERY_STORAGE_URI)/jars/$(REVISION).jar) ;\
+    else \
+    JAR_LOCATION=$$((TEST_STORAGE_URI)/$(NAMESPACE)/jars/$(TOKEN)/$(REVISION).jar) ;\
+    fi \
+    else \
+    JAR_LOCATION=$$((TEST_STORAGE_URI)/$(NAMESPACE)/jars/$(TOKEN)/$(REVISION).jar) ;\
+    fi ;\
+	gsutil -m cp $(SHADOW_JAR) $$(JAR_LOCATION)  ;\
+	echo $$(JAR_LOCATION) > $@  ;\
 
 .PHONY: install-editable
 install-editable: $(PYTHON_VERSION_INFO) $(INIT_SCRIPTS)
